package org.example.usecaseChrome;// Generated by Selenium IDE

import org.example.Utils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class FastSearchTestChrome {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void fastSearch() {
        driver.get("https://fishki.net/");
//        driver.manage().window().setSize(new Dimension(974, 893));
        driver.findElement(By.xpath("/html/body/header/div/nav[2]/ul/li[2]/a")).click();
        driver.findElement(By.xpath("/html/body/header/div/nav[2]/ul/li[2]/ul/li/form/input")).click();
        driver.findElement(By.xpath("/html/body/header/div/nav[2]/ul/li[2]/ul/li/form/input")).sendKeys(Utils.SEARCH_INPUT);
        driver.findElement(By.xpath("/html/body/header/div/nav[2]/ul/li[2]/ul/li/form/button")).click();
        try {
            driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
            System.out.println(driver.findElement(By.xpath("/html/body/div[5]/div[1]/h1/span")).getText());
            assertEquals(Utils.SEARCH_INPUT, driver.findElement(By.xpath("/html/body/div[5]/div[1]/h1/span")).getText());
        } catch (Exception e) {
            System.out.println("A captcha has been detected");
        }
    }
}
