package org.example.usecaseChrome;// Generated by Selenium IDE

import org.example.Utils;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class OpenPaperTestChrome {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void openPaperTestFirefox() throws InterruptedException {
    driver.get("https://fishki.net/");
    try {
      driver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
      driver.findElement(By.xpath("//a/span")).click();
      System.out.println("A captcha has been detected");
      assertEquals(true, driver.findElement(By.xpath("/html/body/div[1]/div/h2")).getText().contains("человек"));
    } catch (Exception e) {
      driver.findElement(By.xpath("//a[2]")).click();
    }
  }
}
