package org.example.usecaseFirefox;// Generated by Selenium IDE
import org.example.Utils;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class LoginTestFirefox {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void loginTestChrome() throws InterruptedException {
        driver.get("https://fishki.net/");
        try {
            driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        } catch (Exception e) {
            System.out.println("Timeout");
        }
//    driver.manage().window().setSize(new Dimension(945, 1012));
        driver.findElement(By.cssSelector(".icon")).click();
        driver.findElement(By.xpath("/html/body/section/div/div/div[2]/div[1]/form/input[4]")).sendKeys("I_want_another_variant");
        driver.findElement(By.xpath("/html/body/section/div/div/div[2]/div[1]/form/input[5]")).sendKeys("wrong_password_12345");
        TimeUnit.SECONDS.sleep(3);
        driver.findElement(By.xpath("/html/body/section/div/div/div[2]/div[1]/form/button")).click();
        {
            WebElement element = driver.findElement(By.xpath("/html/body/header/div/div/ul/li[2]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.xpath("/html/body/header/div/div/ul/li[2]/ul/li[7]/a")).click();
    }
}
